# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - '7.1'
  - '5.6'
  - '5.5'
# Commands to be run before your environment runs.
before_script:
  - composer install
script:
  -phpunit
